### ISSUE TITLE
(B) Логика?

### ISSUE THREAD

**Issue by G0ld3nDr4g0n3301** [kosnvny/absolutely_new_lab3#10]
Предупреждаю,всё,что я пишу - просто рекомендации, ты вольна их игнорить.
У тебя метод act у кнопки принимает зрителей,это неправильно. Потому что я например хочу создать кнопку,которая просто работает,и никто на неё не реагирует. Как мне это сделать с твоим классом? Никак. Потому что реакция,это не свойство кнопки,его следует сделать в Main,а не в других классах.Я бы сделал енам ButtonAction который отнаследовал бы от интерфейса Actable, и в каждом экземпляре энама переопределил бы метод act,который выполнял бы своё действие. Ещё я бы сделал класс Reactions,где перечислил бы реакции,типа смены настроения и т.д. и реализовал бы в них методы реакций. А в классе Person я бы сделал метод react(надо поработать над неймингом) который бы вызывал необходимую реакцию в зависимости от типа нажатой кнопки,например. А тип события я бы засунул в энам EventType, например BUTTON_CHAIR_RED_PUSHED и т.д. Тогда бы мы просто в мейне после нажатия шурупа на кнопку вызывали бы у зрителей через for-each реакции на соответствующие события.Если мы хотим жёстко всё захардкодить,то мы можем сделать,чтобы метод push у шурупа возвращал событие, и отреагировать на него зрителями. Если мы хотим,чтобы всё было гибко - просто подаём на вход react'у тип события, но предупреждаю,тогда получится,что мы можем после нажатия красной кнопки отреагировать на падение шурупа в подвал,например.Выбор за тобой.

**Comment by Vediusse** [comment]
если тебе нужна кнопка на которую никто не реагирует - просто передаешь пустой массив - и следует всю логику подвести к этом, оставив нынешнюю логику

Ну в задание такого нет поэтому это из разряда 🤓

**Comment by G0ld3nDr4g0n3301** [comment]
> если тебе нужна кнопка на которую никто не реагирует - просто передаешь пустой массив - и следует всю логику подвести к этом, оставив нынешнюю логику
> 
> Ну в задание такого нет поэтому это из разряда 🤓

Согласен,это из разряда философии,но всё равно,для дальшейшего расширения было бы лучше сделать так.
