### ISSUE TITLE
(E) бесконечный гамак

### ISSUE THREAD

**Issue by G0ld3nDr4g0n3301** [kosnvny/absolutely_new_lab3#13]
Я могу сделать так
Hammok hammok = new Hammok(40,"имя у мебели?!Шта?!" ,Material.GLASS(тоже недочёт,кстати) );
for (int i = 0; i<100000; i++){
  hammok.humanInHammok(new Person(-‭2 147 483 648‬ , "Да,я могу создать человека с отрицательным здоровьем,и ты мне ничего не сделаешь. АХхахаха. А ещё имя длинное могу сделать,и Javac это схавает!",MOOD.AMAZED, new Space(-155,-346,-346)));
}
Тогда твой код создаст очень много человек, с отрицательным возрастом на пределе int, с очень длинным именем и находящегося в пространстве с отрицательной высотой шириной и длиной. И этим дофигилиардом мутантов человек будет заполнен гамак. "Я точно знаю,нивазможное вазможна!"

**Comment by Vediusse** [comment]
Супер а это к чему - отрицательное здоровье используются к примеру в майнкрафте ( у блока бедрока -1 здоровье) а логика гамака туда ложится человек и происходит действие - он встает и так 100000 раз

Я буду на каждый issue отвечать

**Comment by G0ld3nDr4g0n3301** [comment]
> Супер а это к чему - отрицательное здоровье используются к примеру в майнкрафте ( у блока бедрока -1 здоровье) а логика гамака туда ложится человек и происходит действие - он встает и так 100000 раз
> 
> Я буду на каждый issue отвечать

Да,ты прав,я пересмотрел код и всё ок, человек в гамаке замещается.
